os: osx
osx_image: xcode10.2
language: node_js
node_js: '10'
env:
- ELECTRON_CACHE=$HOME/.cache/electron
- ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
script:
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    yarn dist -l
  else
    yarn dist -wm
  fi
- ls dist
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: vbB7Cf+c/aBRbH9XCKFGytiCDw/Lym9AHLlJYATbJKVs9xUPJpyNW+FFVLxOcbdTPPlz71aaG2OJNO8i0A3sv1RtbBlhPpiieQvsHyemBubCJVXtCgYjDw+c9fJbnwhiBSjbLNyU0eUvJWFceQkcC9+aqlBpFtOYXBq7hBcW3/B0M26qzPvcUdRtFHmUDOcqKGxgQxtJNtfOg4BC7F7p1LHWG+fXouK9h65L3zgxHMwN2ShFtO429e7coWMzpiYF6XwZqxuYaXPZeXEgSZvX6eHnb+t3aVY8dWWOVXDtyal3Dvv7+0a1OKJrpQYaBtfvyFvt6EK0qObPMdk/ZKUHDj8bvP86u5AobTauogfeNKZgg4i3Xp2kUETpcxqfqJcStMacrGAEQFpBj1HacVJp2SCdS4cnS9Xhvu9jAaRJ4sxvOfiUW/mVzdio75m9eUpv9KVbUxi/wHPVpbi2iiSTzGLXCDLiJt+Q6op2ClzJwnKpaJIGxybgiNuUIafEHrhEua9Zjo/kqdTadb1Y/dugQIa2Z7zSa4RHxJIhYs1cr5WbkohJzBiQ4QMdBCIVH4FRmJ0oRynVM2JUL+0Ne9K19gFLQXbtrAFFIFapiMUV/oZmct1oMx9Wl4y91RruL50guF1cGp1tugQe1EvPCXFuzGLGbZcvOwztEUKTBhJOlZY=
  file_glob: true
  file:
    - dist/*.dmg
    - dist/*.exe
  on:
    tags: true
    repo: yqrashawn/conflux-offline-wallet-build
