os: osx
osx_image: xcode10.2
language: node_js
node_js: '10'
env:
- ELECTRON_CACHE=$HOME/.cache/electron
- ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
script:
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    yarn dist -l
  else
    yarn dist -wm
  fi
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
deploy:
  provider: releases
  api_key:
    secure: QS77FVmSh3e2/t4BRZstH+hNgxVUL5Mnj8xDVl8KVyYzenbsXAhZ9lmDIcU6WqgKOwtyYMo5d+9AlXwF9CQbgzy3NfTibuJMR+usRpsn7+miKACVv4nBGhlYZ7oG6pPw77ZOUFwlfoY4kAk70V+rLw4IYxHlhCHKgseGDmLuMYAJ9rn1ylb9cSJS1BK0U0CaPNARaJEvc1Zmb3VfPq0eoYi8X5IMH93PZArgmwTP8v/wCuRhfnWcLCkRDqShmCijtFlber7hLH9zgkHCXQhHfJRo2ak7ww9vXCdXMX73F+E+Q9u8IC9z4I+uD/JTVmT6duCVWWsumwWu8XKQKqhtpEzBv+Y8wp8IIvhVpmMiSGpfi7yhP0wCLTNHUUm3ebujRnAg00cEPR62+qy0HIZtqfmto2KDWdBB2TutVjPW9yCzvupbRQ6cdXdyy3DBjUnDcHlxlDGI12RIxGugADqdHJvJMZg8L/UThsRQYxryxGwYdZUDcLayRFbcKQSddhqPl0NjLKh0Z7XRi9GKQkIGI7/NYJutCdLmpOjRxQxPa2bCfniSaHQyZdQo/8QQYY8irtzYfVaeNk6Stw+st7nrHGzVa6nE80BT3HWDI5BONLsqT/vYf5YN0fZ0HQB5Fa/rRVwPtQgAfQ+1fAy/MwZ73t3NqD0bWwnvaLDR6meT2fc=
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
    repo: yqrashawn/conflux-offline-wallet-build
